version: '3.8'

services:

  db:
    image: postgres
    container_name: data_base_pg
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: data_base
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - compose-bridge

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - redis_network

  server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5024
      - ASPNETCORE_HTTPS_PORTS=5024
    container_name: auth-rol.asp.net
    image: ${DOCKER_REGISTRY-}auth-rol.asp.net
    build:
      context: .
      dockerfile: Auth-Rol.ASP.NET/Dockerfile
    ports:
      - "5024:5024"
    networks:
      - compose-bridge
      - redis_network
    depends_on:
      - db 

volumes:
  redis_data:

networks:
  redis_network:
    driver: bridge

  compose-bridge:
    driver: bridge


