version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: handler_queries
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/data_base
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: npm run dev

  db:
    image: postgres
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      # - DATABASE_HOST = 127.0.0.1
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data_base
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


      
